Summon new features 24.06.00
Aspen-Discovery/aspen-discovery pull request #1807
Opened 2024-05-14 09:27 UTC by AlexanderBlanchardAC

This patch adds several new features to Summon, including the ability to control whether the Explore More Section is visible and to control whether available book covers are displayed when using the Summon Searcher.

Testing Book Covers:
This patch adds the ability to use only book covers generated by Aspen or to include those available from the API when carrying out a Summon Search. Choosing to use generated covers only increases the speed at which Summon loads results.

TEST PLAN:
(After applying patch).

1. Carry out a Summon Search as usual. You will notice that you are returned book covers that are generated by Aspen.
2. Navigate to Primary Configurations -> Library Systems and then edit whichever Library is your default.
3. Scroll to the Summon Section and check the tick box that is labelled, 'Show Available Covers in Summon.'
4. Click to save your changes and repeat your search.
5. Notice that the covers you are returned are now a mix of generated covers and actual book covers from the API - note that your results may load more slowly with this option enabled.

Testing Explore More Section:
This patch adds the ability to control whether the Explore More Section is visible in search results. By default, it is set to visible.

TEST PLAN

1. Add the patch
2. Carry out a a Summon Search
3. Note that part way down your results list you will have a box labelled 'Explore More.'
4. Navigate to the Layout Settings: Aspen Administration -> Theme and Layout -> Layout Settings.
5. Within the layout settings, scroll to the checkbox labelled 'Show Explore More Options' and untick it.
6. Repeat your search and notice that this time you do not have the 'Explore More' box in your results.

2024-05-20 16:50 UTC, mdnoble73 requested changes
See comments in individual files

2024-05-20 16:50 UTC, mdnoble73 commented on code/folio_export/folio_export.jar
Can we remove this from the PR?

2024-05-20 16:50 UTC, mdnoble73 commented on code/web/interface/themes/responsive/images/summon.png:Zone.Identifier
What is this used for?

2024-05-20 16:50 UTC, mdnoble73 commented on code/web/release_notes/24.06.00.MD
> +- Added option for Explore More bar to be hidden (*AB*)
Can you add a comment with your name(s) ahead of these changes just to make merges easier during lots of updates

2024-05-20 16:50 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/23.12.01.php
Let's remove this change

2024-05-20 16:50 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/24.05.00.php
Let's also remove this change

2024-05-20 16:50 UTC, mdnoble73 commented on code/web/sys/Theming/LayoutSetting.php
Explore more is a key feature of Aspen if we want to disable Explore more, I think we'll want more control than just on and off everywhere.  Can you explain more what your partner wants?

2024-05-21 14:20 UTC, AlexanderBlanchardAC commented on code/web/interface/themes/responsive/images/summon.png:Zone.Identifier
This image is used for the Summon option in the Explore More section.

2024-05-21 14:49 UTC, mdnoble73 commented on code/web/interface/themes/responsive/images/summon.png:Zone.Identifier
I was wondering about the file with the Zone.Identifier at the end, I haven't seen that type of file before

2024-05-21 17:07 UTC, closed without merging