Summon new features updated
Aspen-Discovery/aspen-discovery pull request #1820
Opened 2024-05-28 10:34 UTC by AlexanderBlanchardAC

Updates to Summon - removed Explore More Section changes - created new branch for these changes.

2024-06-03 17:02 UTC, mdnoble73 requested changes
Did a quick search in summon for global warming and got the attached notices: 
![image](https://github.com/Aspen-Discovery/aspen-discovery/assets/1325839/347e01a4-96b8-4886-aa1e-22c5cd6270f6)

2024-06-03 17:02 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/24.06.00.php
> +		//alexander - PTFS Europe
Can you move this bit to the other pull request?

2024-06-04 17:07 UTC, AlexanderBlanchardAC commented
> Did a quick search in summon for global warming and got the attached notices: ![image](https://private-user-images.githubusercontent.com/1325839/336162014-347e01a4-96b8-4886-aa1e-22c5cd6270f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MjEwMjEsIm5iZiI6MTcxNzUyMDcyMSwicGF0aCI6Ii8xMzI1ODM5LzMzNjE2MjAxNC0zNDdlMDFhNC05NmI4LTQ4ODYtYWExZS0yMmM1Y2Q2MjcwZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDRUMTcwNTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDVmYzM4YWYzOGQ3ZWI0NDc0MGE0ZjI4ZjYzMTQ0ZjA5OGM0NDY1MGFjZDY0YzBkM2FmMmY0MTE3MzE3MmRiMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7ePvX8eV7OaVUVIwRwXsyoOfCfKVSMU3TY58J22X3Do)

I don't seem to be getting this error. I added a check before the $isApplied is created that I hope addresses it.

2024-06-05 16:48 UTC, mdnoble73 approved these changes

2024-06-05 16:52 UTC, merged