SMTP Setting
Aspen-Discovery/aspen-discovery pull request #1850
Opened 2024-06-12 14:59 UTC by ammopt

2024-06-18 14:32 UTC, mdnoble73 requested changes
Looks great.  Just a few little functionality changes in the sending to look at.

2024-06-18 14:32 UTC, mdnoble73 commented on code/web/sys/Email/SMTPSetting.php
> +				'default' => 'heyo',
Let's remove the default value here

2024-06-18 14:32 UTC, mdnoble73 commented on code/web/sys/Email/SMTPSetting.php
> +		$mail->FromName = 'Aspen Discovery';
Should the From name be customizable? I could see libraries wanting to change that.

2024-06-18 14:32 UTC, mdnoble73 commented on code/web/sys/Email/SMTPSetting.php
> +		$mail->addAddress($to);
We have a few cases where we send to multiple email addresses separated by semi-colons.  We should make sure we support that.

2024-06-18 14:32 UTC, mdnoble73 commented on code/web/sys/Email/SMTPSetting.php
> +		$mail->From = $this->from_address;
We have a few cases where we override the from address in the other Email methods.

2024-06-20 13:53 UTC, ammopt commented on code/web/sys/Email/SMTPSetting.php
> +				'default' => 'heyo',
Addressed in https://github.com/Aspen-Discovery/aspen-discovery/pull/1850/commits/abf2b2fffb84394cd015b7ffa3ae09ac1fa5eeae

2024-06-20 13:54 UTC, ammopt commented on code/web/sys/Email/SMTPSetting.php
> +		$mail->FromName = 'Aspen Discovery';
Addressed in https://github.com/Aspen-Discovery/aspen-discovery/pull/1850/commits/904c78302c1a37ba72180bfba0a43ca95700e0c4

2024-06-20 13:54 UTC, ammopt commented on code/web/sys/Email/SMTPSetting.php
> +		$mail->addAddress($to);
Addressed in https://github.com/Aspen-Discovery/aspen-discovery/pull/1850/commits/19b0e48f97022ce09818dfec67727cc01af48108

2024-06-20 13:58 UTC, ammopt commented on code/web/sys/Email/SMTPSetting.php
> +		$mail->From = $this->from_address;
Thank you so much for your review, Mark. Apologies for some of the 'basic' mishaps!
I don't fully understand what is required here though, can you please explain further?

From what I see in the other Email methods, they both utilize the configured 'from' value.
SendGrid:
```
$apiBody->from = new stdClass();
$apiBody->from->email = $sendGridSettings->fromAddress;
```

Amazon:
`$sesMessage->setFrom($this->fromAddress);`

2024-06-25 21:25 UTC, mdnoble73 approved these changes

2024-06-25 21:25 UTC, mdnoble73 commented on code/web/sys/Email/SMTPSetting.php
> +		$mail->From = $this->from_address;
My apologies, I misremembered that

2024-06-25 21:25 UTC, merged