Add new apache's rules
Aspen-Discovery/aspen-discovery pull request #1869
Opened 2024-06-18 20:58 UTC by lucasmontoya13

- New rules have been added to the httpd configuration file to allow Aspen to switch to other languages even when users fill out forms.

2024-07-03 17:24 UTC, mdnoble73 requested changes
Looks like a few of the RewriteRules need to be adjusted still.  Is it possible to achieve the same thing by adjusting the logic in loadModuleActionId within index.php?

2024-07-03 17:24 UTC, mdnoble73 commented on sites/default/httpd-default.conf
> +		RewriteRule   ^([^/]+)/(.+)$                index.php?module=$1&action=Home         [B,L,QSA]
I believe these rules got reversed:
RewriteRule   ^([^/]+)$                     index.php?module=$1&action=$2           [B,L,QSA]
does not have a second capturing group so it should default to Home. 
RewriteRule   ^([^/]+)/(.+)$                index.php?module=$1&action=Home         [B,L,QSA]
does have to capturing groups so the second should be passed to index.php

2024-07-03 17:24 UTC, mdnoble73 commented on sites/default/httpd-default.conf
> +		RewriteRule   ^([^/]+)/(.+)$                index.php?module=$1&action=Home         [B,L,QSA]
This will need to get changed in all the files

2024-07-04 15:39 UTC, lucasmontoya13 commented
Sorry, i haven't seen the first comment! I'll try to fix it in index.php

2024-07-09 20:39 UTC, mdnoble73 commented
Do you want to keep this PR open or do you think you can do it in index.php? I'm fine either way.

2024-07-25 15:46 UTC, closed without merging