Catalog offline mode, Add to List button fixes
Aspen-Discovery/aspen-discovery pull request #1870
Opened 2024-06-20 13:34 UTC by Abhyastamita

- Add to List now shows in 'Catalog Offline, login allowed with eContent Active' mode for modals.
- Add to List now does not show for List searches.

2024-06-24 21:01 UTC, Abhyastamita commented
This PR now also includes an unrelated change to translate the error message from OverDrive for trying to return a Kindle book.

2024-06-25 16:05 UTC, mdnoble73 requested changes
Just a couple of space vs. tab fixes

2024-06-25 16:05 UTC, mdnoble73 commented on code/web/Drivers/OverDriveDriver.php
> +                if ($response->message == "An unmapped error has occurred. '7'") {
Can you fix tabs vs. spaces for this?

2024-06-25 18:43 UTC, Abhyastamita commented
I think all the tabs are fixed now.

2024-06-25 20:29 UTC, mdnoble73 approved these changes

2024-06-25 20:29 UTC, merged