Show summon search tools
Aspen-Discovery/aspen-discovery pull request #1901
Opened 2024-07-12 07:54 UTC by AlexanderBlanchardAC

Test Plan:

1. Before applying patch, set up Summon and carry out a search.
2. Notice that there is no checkbox to hide covers or option to switch between list and covers view at the top of the page.
3. Repeat the above with an Ebsco EDS search.
4. Apply the patch.
5. Notice that when you carry out a Summon Search now, the search tools are at the top of the screen as they are in Ebsco EDS and checking the hide covers box refreshes the page and returns results without the covers.

2024-07-21 19:54 UTC, mdnoble73 commented
The hide covers action works great, but the toggle between covers mode and list mode does not work. You could just remove the covers and list mode toggles rather than implementing them since covers mode is unlikely to be used for this type of resource.  I did the same for EBSCO and EBSCOhost in 24.08 if you want an example of how I did that.

2024-07-21 19:57 UTC, mdnoble73 requested changes
This will need release notes, also see main discussion thread

2024-07-22 09:16 UTC, AlexanderBlanchardAC commented
> The hide covers action works great, but the toggle between covers mode and list mode does not work. You could just remove the covers and list mode toggles rather than implementing them since covers mode is unlikely to be used for this type of resource. I did the same for EBSCO and EBSCOhost in 24.08 if you want an example of how I did that.

I have removed the covers / list option

2024-07-22 09:16 UTC, AlexanderBlanchardAC commented
> This will need release notes, also see main discussion thread

Sorry, MD file updated.

2024-07-29 18:06 UTC, mdnoble73 requested changes
This change removes those tools from all searches which isn't what we want.

2024-07-29 18:06 UTC, mdnoble73 commented on code/web/interface/themes/responsive/Search/search-toolbar.tpl
Changing this file removes those options from all searches not just summon.

2024-07-29 18:06 UTC, mdnoble73 commented on code/web/interface/themes/responsive/Search/results-displayMode-toggle.tpl
Changing this file removes those options from all searches not just summon.

2024-07-30 10:40 UTC, closed without merging