24.09.00 cookie management
Aspen-Discovery/aspen-discovery pull request #1952
Opened 2024-08-02 19:08 UTC by AlexanderBlanchardAC

2024-08-12 16:41 UTC, mdnoble73 requested changes
See inline changes, let me know if you want to meet to go through anything.

2024-08-12 16:41 UTC, mdnoble73 commented on code/web/services/MyAccount/MyCookiePreferences.php
This file needs to be cleaned up for tabs so everything gets indented properly.

2024-08-12 16:41 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/24.09.00.php
> +		'update_cookie_management_preferences_more_options' => [
This would currently set everyone up with tracking turned off which is appropriate if Cookie Consent is enabled. However, if cookie consent is disabled, we'll want to make sure that users are all opted in to tracking or else all data will be automatically deleted after cron runs the first time.

2024-08-12 16:41 UTC, mdnoble73 commented on code/cron/src/com/turning_leaf_technologies/cron/DatabaseCleanup.java
> +		removeExternalSearchTracking(dbConn, logger, processLog);
We will also want to clean up previously stored tracking data for Events, Websites, Open Archives, etc. Do we want to do the cleanup in cron or at the point where the user opts out? Doing it at the point where the user actually opts out is probably cleaner. We can cleanup existing data before this logic is added in the database updates.

2024-08-12 16:41 UTC, mdnoble73 commented on code/web/Drivers/Axis360Driver.php
> +		$userObj = UserAccount::getActiveUserObj();
The $user object is the same in this case as UserAccount::getActiveUserObj() so that call is not needed.

2024-08-12 16:41 UTC, mdnoble73 commented on code/web/Drivers/Axis360Driver.php
> +		if ($userAxis360Tracking && $library->cookieStorageConsent) {
Should this be $userAxis360Tracking || !$library->cookieStorageConsent? That way the tracking is done if the library has not enabled cookie consent or the user has opted in.

2024-08-12 16:41 UTC, mdnoble73 commented on code/web/Drivers/CloudLibraryDriver.php
> +		if ($userCloudLibraryTracking && $library->cookieStorageConsent) {
Should probably be || !$library->cookieStorageConsent

2024-08-12 16:41 UTC, mdnoble73 commented on code/web/Drivers/HooplaDriver.php
> +		if ($userHooplaTracking && $library->cookieStorageConsent) {
Should probably be || !$library->cookieStorageConsent

2024-08-12 16:41 UTC, mdnoble73 commented on code/web/Drivers/OverDriveDriver.php
> +		if ($userOverDriveTracking && $library->cookieStorageConsent) {
Should probably be || !$library->cookieStorageConsent

2024-08-12 16:41 UTC, mdnoble73 commented on code/web/Drivers/PalaceProjectDriver.php
> +		if ($userPalaceProjectTracking && $library->cookieStorageConsent) {
Should probably be || !$library->cookieStorageConsent

2024-08-12 16:41 UTC, mdnoble73 commented on code/web/index.php
> +				$userEventsPref = $cookie['UserEvents'];
These variables are not currently used for anything

2024-08-12 16:41 UTC, mdnoble73 commented on code/web/Drivers/Axis360Driver.php
> +		$userAxis360Tracking = $userObj->userCookiePreferenceExternalSearchServices;
This should check $user->userCookiePreferenceAnalytics

2024-08-12 16:41 UTC, mdnoble73 commented on code/web/Drivers/CloudLibraryDriver.php
> +		$userCloudLibraryTracking = $userObj->userCookiePreferenceExternalSearchServices;
This should check $user->userCookiePreferenceAnalytics

2024-08-12 16:41 UTC, mdnoble73 commented on code/web/Drivers/HooplaDriver.php
> +		$userHooplaTracking = $userObj->userCookiePreferenceExternalSearchServices;
This should check $user->userCookiePreferenceAnalytics

2024-08-12 16:41 UTC, mdnoble73 commented on code/web/Drivers/OverDriveDriver.php
> +		$userOverDriveTracking = $userObj->userCookiePreferenceExternalSearchServices;
This should check $user->userCookiePreferenceAnalytics

2024-08-12 16:41 UTC, mdnoble73 commented on code/web/Drivers/PalaceProjectDriver.php
> +		$userPalaceProjectTracking = $userObj->userCookiePreferenceExternalSearchServices;
This should check $user->userCookiePreferenceAnalytics

2024-08-12 16:41 UTC, mdnoble73 commented on code/web/interface/themes/responsive/AJAX/cookieManagement.tpl
> +        UserEvents: {$profile->userCookiePreferenceEvents},
We can remove UserEvents, UserOpenArchives, UserWebsite, and UserExternalSearchServices I think and just use Analytics

2024-08-12 16:41 UTC, mdnoble73 commented on code/web/interface/themes/responsive/AJAX/cookieManagement.tpl
> +         {if array_key_exists('Axis 360', $enabledModules) || array_key_exists('EBSCO EDS', $enabledModules) || array_key_exists('EBSCOhost', $enabledModules) || array_key_exists('Summon', $enabledMo
This is going to be a bit confusing to users and they will likely always just have them all on or all off. Let's just do all of the tracking or not tracking based off the Analytics, since that encompasses all of the sub categories.

2024-08-12 16:41 UTC, mdnoble73 commented on code/web/interface/themes/responsive/MyAccount/myCookiePreferences.tpl
> +				{if !empty($showUsernameField)}
Username shouldn't be on the cookie preferences page

2024-08-12 16:41 UTC, mdnoble73 commented on code/web/interface/themes/responsive/MyAccount/myCookiePreferences.tpl
> +							{if array_key_exists('Axis 360', $enabledModules) || array_key_exists('EBSCO EDS', $enabledModules) || array_key_exists('EBSCOhost', $enabledModules) || array_key_exists('Summon', $enabledModu
Let's just leave this as anayltyics

2024-08-12 16:41 UTC, mdnoble73 commented on code/web/interface/themes/responsive/cookie-consent.tpl
> +            UserEvents: {$profile->userCookiePreferenceEvents},
I think these can all be condensed to just Analytics on/off

2024-08-14 12:11 UTC, AlexanderBlanchardAC commented on code/web/interface/themes/responsive/AJAX/cookieManagement.tpl
> +        UserEvents: {$profile->userCookiePreferenceEvents},
Analytics is what Jacob put in originally, which I believe is Google analytics. If we group these we would need to have another drop down to explain what users are agreeing to in order to be compliant with GDPR.

2024-09-03 22:54 UTC, mdnoble73 requested changes
I'll keep reviewing in the morning, but wanted to get you what I have so far.

2024-09-03 22:54 UTC, mdnoble73 commented on code/web/sys/LibraryLocation/Library.php
> +			error_log("UPDATE CALLED");
If this is needed, it should use Aspen Logging to log to messages.log

2024-09-03 22:54 UTC, mdnoble73 commented on code/web/sys/LibraryLocation/Library.php
> +			error_log("Library ID is not set.");
If this is needed, it should use Aspen Logging to log to messages.log

2024-09-03 22:54 UTC, mdnoble73 commented on code/web/sys/LibraryLocation/Library.php
> +				$user->userCookiePreferenceLocalAnalytics = $this->cookieStorageConsent ==1 ? 0 : 1;
Do we need to consider cases where a library turns analytics off, then back on, then back off? Or on/off/on? Should patron preferences be remembered in those cases?

2024-09-03 22:54 UTC, mdnoble73 commented on code/web/sys/LibraryLocation/Library.php
> +			$this->updateLocalAnalyticsPreferences();
We shouldn't need to do this on insert since there will be no users for a new user.

2024-09-03 22:54 UTC, mdnoble73 commented on code/web/sys/LibraryLocation/Library.php
> +	public function updateLocalAnalyticsPreferences(){
Can you add more comments to this function to explain what is happening?

2024-09-03 22:54 UTC, mdnoble73 commented on code/web/sys/LibraryLocation/Library.php
> +			$this->updateLocalAnalyticsPreferences();
To improve performance we probably only want to do this if the relevant cookie consent fields are changed. You can check the _changedFields field to see if it was updated.

2024-09-03 22:54 UTC, mdnoble73 commented on code/web/services/MyAccount/MyCookiePreferences.php
> +			$userSummonUsage->find();
These can all be optimized by calling: 
->delete(true)
rather than looping through all of the objects one at a time and deleting them.

2024-09-03 22:54 UTC, mdnoble73 commented on code/web/interface/themes/responsive/MyAccount/myCookiePreferences.tpl
> +						<strong class="control-label" style="margin-bottom:10px;">{translate text="Thrid Party Analytics" isPublicFacing=true}:</strong>&nbsp;
This should be Third not Thrid

2024-09-03 22:54 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/24.09.00.php
> +			'descritpion' => 'Add a column to hold local analytics tracking choices',
The description key is misspelled here

2024-09-05 16:42 UTC, AlexanderBlanchardAC commented on code/web/sys/LibraryLocation/Library.php
> +				$user->userCookiePreferenceLocalAnalytics = $this->cookieStorageConsent ==1 ? 0 : 1;
I'm not sure if I have understood the use case here correctly. If a library has cookieConsentEnabled tuned off, the default userCookiePreferenceLocalAnalytics is 1 and can't be changed by the user, if the library turns cookieConsentEnabled on, and the user opts in to localAnalytics, cookiePreferenceLocalAnalytics is set to 1, if the library then turns cookieConsentEnabled off again, cookiePreferneceLocalAnalytics would default to 1 - do you mean check if the value of cookiePreferenceLocalAnalytics is already what we would be setting it to and if it is, ignore it? Sorry, I seem to have made that very complicated.

2024-09-05 17:47 UTC, mdnoble73 requested changes
Took another pass at this. Can you review comments and let me know when it is ready again? 

Thanks!

2024-09-05 17:47 UTC, mdnoble73 commented on code/cron/src/com/turning_leaf_technologies/cron/DatabaseCleanup.java
> +			PreparedStatement checkAnalyticsDataClearedStmt = dbConn.prepareStatement("SELECT analyticsDataCleared FROM user WHERE libraryCookieStorageConsent = 1");
I don't see a case where analyticsDataCleared is set to true in the code. Does this function need to set analyticsDataCleared after clearing the data. Also, this check only checks the value of the first user in the database. Do we need to check and set the value for each user?

2024-09-05 17:47 UTC, mdnoble73 commented on code/web/index.php
> +				$userEventsPref = $cookie['UserEvents'];
Can we remove these if they are not currently used for anything?

2024-09-05 17:47 UTC, mdnoble73 commented on code/web/interface/themes/responsive/AJAX/cookieManagement.tpl
> +                    {translate text="By checking this box you are giving consent to local analytics tracking. Aspen will collect information about your usage of the folllwing services: "}
folllwing is misspelled

2024-09-05 17:47 UTC, mdnoble73 commented on code/web/interface/themes/responsive/AJAX/cookieManagement.tpl
> +                        <li>{translate text="Axis 360" isPublicFacing=true}</li>
The proper name for Axis 360 now is Boundless

2024-09-05 17:47 UTC, mdnoble73 commented on code/web/interface/themes/responsive/AJAX/cookieManagement.tpl
> +                            <li>{translate text="Cloud Library" isPublicFacing=true}</li>
This should be cloudLibrary

2024-09-05 17:47 UTC, mdnoble73 commented on code/web/interface/themes/responsive/AJAX/cookieManagement.tpl
> +                            <li>{translate text="Ebsco Eds" isPublicFacing=true}</li>
This should be EBSCO EDS

2024-09-05 17:47 UTC, mdnoble73 commented on code/web/interface/themes/responsive/AJAX/cookieManagement.tpl
> +                            <li>{translate text="Overdrive" isPublicFacing=true}</li>
There is a translatable name for OverDrive stored within OverDrive settings for the library. See the OverDriveDriver

2024-09-05 17:47 UTC, mdnoble73 commented on code/web/interface/themes/responsive/AJAX/cookieManagement.tpl
> +                            <li>{translate text="Side Loaded eContent" isPublicFacing=true}</li>
Not sure what the best term is for this. We never show the term Side Load to patrons since it doesn't really make sense to them.

2024-09-05 17:47 UTC, mdnoble73 commented on code/web/interface/themes/responsive/AJAX/cookieManagement.tpl
> +                            <li>{translate text="Web Indexer" isPublicFacing=true}</li>
Not sure what the best term is for this either, maybe Library Website?

2024-09-05 17:47 UTC, mdnoble73 commented on code/web/interface/themes/responsive/MyAccount/cookieConsentPrivacyPolicy.tpl
> +        Policy
This will need to be customizable by the library

2024-09-05 17:47 UTC, mdnoble73 commented on code/web/services/Admin/CookieConsentPrivacyPolicy.php
This probably should go in /Help rather than /Admin

2024-09-05 19:51 UTC, mdnoble73 commented on code/web/sys/LibraryLocation/Library.php
> +				$user->userCookiePreferenceLocalAnalytics = $this->cookieStorageConsent ==1 ? 0 : 1;
I'm probably over complicating it too. I'm worried about cases where a user's data gets lost if a library accidentally toggles something off and then on, but also if the toggle it off and then on, historic data probably should go away.

2024-09-09 11:03 UTC, closed without merging