Change order of permission changes for debian
Aspen-Discovery/aspen-discovery pull request #1953
Opened 2024-08-02 21:28 UTC by lizrea

Logs directory was getting wrong ownership, moving the logs directory ownership command to after the permission changes for the parent should fix it

to test: 
run updateSitePermissions.sh <sitename>, observe that the permissions for var/log/aspen-discovery/<site>/logs are www-data:aspen_apache

apply this patch
run updateSitePermissions.sh <sitename>, observer that the permissions for /var/log/aspen-dsicovery/<site>/logs are now aspen:aspen

2024-08-02 21:33 UTC, mdnoble73 commented
Can you add release notes see: https://dev.aspendiscovery.org/release-notes also do you want this in a version earlier than 24.09?  24.09 will go out in September and Debian upgrades will be on versions 24.07.02 or 24.08 primarily.

2024-08-06 14:03 UTC, lizrea commented
yep happy to do that

2024-08-12 16:51 UTC, mdnoble73 requested changes
Please add release notes

2024-08-21 20:53 UTC, mdnoble73 approved these changes

2024-08-21 20:53 UTC, mdnoble73 commented
I'll add release notes and update centos as well

2024-08-21 20:53 UTC, merged