Add pagination to Usage by User Agent Report
Aspen-Discovery/aspen-discovery pull request #1971
Opened 2024-08-09 19:44 UTC by Abhyastamita

- Added pagination to Usage by User Agent Report
- Updated release notes

2024-08-12 13:34 UTC, mdnoble73 requested changes

2024-08-12 13:34 UTC, mdnoble73 commented on code/web/services/Admin/UsageByUserAgent.php
> +		$pageSize = isset($_REQUEST['pageSize']) ? $_REQUEST['pageSize'] : 5; // to adjust number of items listed on a page
Let's make the default page size 30 to match the selections in the menu.

2024-08-12 13:34 UTC, mdnoble73 commented on code/web/services/Admin/UsageByUserAgent.php
>  		$allUserAgents = $userAgent->fetchAll('id', 'userAgent');
The fetchAll statement redoes the search from the previous statement.  This just needs to be switched to a loop through the results and store the values appropriately.

2024-08-16 12:43 UTC, Abhyastamita commented on code/web/services/Admin/UsageByUserAgent.php
>  		$allUserAgents = $userAgent->fetchAll('id', 'userAgent');
Thanks Mark!  This is fixed now.

2024-08-16 12:45 UTC, Abhyastamita commented on code/web/services/Admin/UsageByUserAgent.php
> +		$pageSize = isset($_REQUEST['pageSize']) ? $_REQUEST['pageSize'] : 5; // to adjust number of items listed on a page
Thanks!  I changed it to 30.

2024-08-21 21:04 UTC, mdnoble73 approved these changes

2024-08-21 21:04 UTC, merged