Properly close the connections to Koha from Aspen
Aspen-Discovery/aspen-discovery pull request #1984
Opened 2024-08-15 14:28 UTC by kylemhall

It is best practice to close all database connections after the data from a query has been ingested and parsed.

This change calls close() on all mysqli result sets that do not already call close after use.

No changes in Aspen behavior should be noted, but this should result in a reduction of used connections to the database.

2024-08-15 17:43 UTC, mdnoble73 requested changes
Please add release notes as well as a test plan

2024-08-19 20:31 UTC, mdnoble73 requested changes
See inline notes

2024-08-19 20:31 UTC, mdnoble73 commented on code/web/Drivers/Koha.php
> +			$claimsReturnedResults->close();
This will not work in cases where $claimsReturnedResults is false. This line should have been left where it was.

2024-08-19 20:31 UTC, mdnoble73 commented on code/web/Drivers/Koha.php
>  						return $newUser;
Before returning $newUser, the database connection should also be closed.

2024-08-19 20:31 UTC, mdnoble73 commented on code/web/Drivers/Koha.php
>  								return $expiredPasswordResult;
$lookupUserResult should also be closed here

2024-08-19 20:31 UTC, mdnoble73 commented on code/web/Drivers/Koha.php
> +					$lookupUserResult->close();
There are several returns in the block between where the SQL statement is opened and the close statement where the connection should be closed.

2024-08-19 20:31 UTC, mdnoble73 commented on code/web/Drivers/Koha.php
> +			$lookupUserResult->close();
We should also close if the $user->insert() statement fails

2024-08-19 20:31 UTC, mdnoble73 commented on code/web/Drivers/Koha.php
> +			    $renewResults = mysqli_query($this->dbConnection, $renewSql);
If this call is moved to after the renewal is done, the renewal count should not be incremented

2024-08-19 20:31 UTC, mdnoble73 commented on code/web/Drivers/Koha.php
> +		$lookupUserResult->close();
This will also need to be done if we return $newUser

2024-08-19 20:31 UTC, mdnoble73 commented on code/web/Drivers/Koha.php
> +		$results->close();
$results is already closed by the time we get here. The only way it will not be is if $results is false so this will throw an error

2024-08-19 20:31 UTC, mdnoble73 commented on code/web/Drivers/Koha.php
>  				return $curRow['userId'];
$results needs to be closed before the return statement as well

2024-08-19 20:31 UTC, mdnoble73 commented on code/web/Drivers/Koha.php
> +			$results->close();
$results also needs to be closed if we return in the previous bolck

2024-08-19 20:31 UTC, mdnoble73 commented on code/web/Drivers/Koha.php
> +			$results->close();
Moving this out of the block will cause an error if $results is false

2024-08-19 20:31 UTC, mdnoble73 commented on code/web/Drivers/Koha.php
> +			$lookupUserRow->close();
This is the wrong variable

2024-08-19 20:31 UTC, mdnoble73 commented on code/web/Drivers/Koha.php
> +
This needs to be before the return statement

2024-08-19 20:31 UTC, mdnoble73 commented on code/web/Drivers/Koha.php
> +			$results->close();
This needs to be within the block checking if results is false

2024-08-20 12:13 UTC, kylemhall commented on code/web/Drivers/Koha.php
> +			$lookupUserResult->close();
Actually, this line is actually superfluous and I'm removing it in the update. That resultset is already closed right after the call to  `fetch_assoc` so there is no need to close if the insert fails, as it has already been closed!

2024-08-20 16:44 UTC, kylemhall commented
@mdnoble73 I've updated the branch! I amended the original commit to include those changes. If you'd rather I put them in a separate commit just let me know!

2024-08-21 21:14 UTC, mdnoble73 requested changes
Indenting on this file does not match coding style for many of the changed lines. Should use tabs rather than spaces.

2024-08-22 21:41 UTC, mdnoble73 approved these changes

2024-08-22 21:44 UTC, merged