Docker entrypoint updates
Aspen-Discovery/aspen-discovery pull request #2032
Opened 2024-08-29 19:07 UTC by tomascohen

In order to test this enhancements, you will need to build your own image out of this patchset.

```shell
docker build . -f docker/Dockerfile -t aspendiscovery/aspen
```

After that, follow the README to launch Aspen using the latest `docker-compose.yml` file.

2024-08-29 21:07 UTC, kylemhall commented on docker/files/scripts/createDirs.php
> -if (count($argv) == 1) {
Can we use getopt here instead perhaps?

2024-08-30 11:45 UTC, tomascohen commented on docker/files/scripts/createDirs.php
> -if (count($argv) == 1) {
I'd agree. Follow-up pull request?

2024-09-03 12:13 UTC, lucasmontoya13 commented
I was able to test these changes in a new instance and everything works well. Splitting the start up script resolves the conflict between services and keeps the containers alive

2024-09-03 16:30 UTC, kylemhall approved these changes

2024-09-03 18:47 UTC, mdnoble73 requested changes

2024-09-03 18:47 UTC, mdnoble73 commented on docker/files/scripts/start.sh
> +# FIXME: This seems to be creating dirs like images/images, etc
@tomascohen do you want a fix in place for this before the PR is merged or do you want to handle this in a followup request?

2024-09-03 18:47 UTC, mdnoble73 commented on docker/files/scripts/start.sh
> +# FIXME: We should probably run Apache in foreground instead. We need to
@tomascohen do you want this to be fixed before merge?

2024-09-03 18:47 UTC, mdnoble73 commented on docker/files/scripts/start.sh
>  curl -k http://"$SITE_NAME"/API/SystemAPI?method=runPendingDatabaseUpdates
Are we setting docker up with SSL enabled? If so, this should be https. If not, we will need to let system administrators know how to setup SSL before they use the docker image in production.

2024-09-03 19:03 UTC, tomascohen commented on docker/files/scripts/start.sh
> +# FIXME: We should probably run Apache in foreground instead. We need to
This is a longer term thing. Not a blocker. I just let the FIXME in place so we don't forget.

2024-09-03 19:04 UTC, tomascohen commented on docker/files/scripts/start.sh
>  curl -k http://"$SITE_NAME"/API/SystemAPI?method=runPendingDatabaseUpdates
Administrators using the Docker images will need to learn how to set a reverse proxy that would do the SSL termination itself. This is because this is designed to run many backend instances if required in a HA setup.

2024-09-03 19:08 UTC, tomascohen commented on docker/files/scripts/start.sh
> +# FIXME: This seems to be creating dirs like images/images, etc
I think this deserves a separate ticket. Because the solution is to have those dirs on a separate path on the filesystem and is a bit of a bolder fix.

2024-09-03 19:09 UTC, tomascohen commented
Is my last commit (Release notes) failing because of the last newline that my editor added?

2024-09-03 19:47 UTC, tomascohen commented
I've rebased the last patch (using Github's builtin tool). I wanted to mention that the failed check (check_tabs_vs_spaces) is a false positive, as my spaces changes are made on purpose so the output is cleaner to read. I'm indenting things properly, etc.

2024-09-03 20:39 UTC, mdnoble73 commented
No worries, that tabs vs/spaces check still doesn't work, I've been manually verifying as needed.

2024-09-03 20:39 UTC, merged