Add flexibility in date formatting for OpenArchives collections
Aspen-Discovery/aspen-discovery pull request #2035
Opened 2024-08-30 16:40 UTC by Howell-Carnegie

This includes a additional setting Open Archives > Collections > Date Formatting to allow a choice to use the existing date formatting or use the date as is from the Open Archive. The SOLR schema needed to have the date field as a String instead of a Date to allow for this flexibility.

2024-09-03 21:21 UTC, mdnoble73 requested changes
Looks great, just a few minor changes

2024-09-03 21:21 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/24.09.00.php
> +				'ALTER TABLE open_archives_collection ADD COLUMN dateFormatting varchar(10) default "yes_format"',
Typically we would do this with a TINYINT column, but this definitely works as well.

2024-09-03 21:21 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/24.09.00.php
> +				'UPDATE open_archives_collection set dateFormatting = "yes_format"',
This isn't technically needed since the default will apply to any existing rows when the column is created.

2024-09-03 21:21 UTC, mdnoble73 commented on code/oai_indexer/src/com/turning_leaf_technologies/oai/OAISolrRecord.java
> +import java.util.Objects;
This declaration isn't needed and can be removed.

2024-09-03 21:21 UTC, mdnoble73 commented on data_dir_setup/solr7/open_archives/conf/schema.xml
> +<!--		<fieldType name="date" class="DatePointField"/>-->
We can leave the date field type defined as DatePointField since the type is changed below.

2024-09-03 21:21 UTC, mdnoble73 commented on data_dir_setup/solr7/open_archives/conf/schema.xml
> +		<field name="date" type="searchable_text_minimal_stem" indexed="true" stored="true" multiValued="true" required="false"/>
This can be an unchanged_string and does not need to be indexed since it is only used for dispaly and not faceting.

2024-09-11 18:38 UTC, Howell-Carnegie commented on data_dir_setup/solr7/open_archives/conf/schema.xml
> +<!--		<fieldType name="date" class="DatePointField"/>-->
It seems like Solr would treat that field like a date point instead of a string if I left the class as "DatePointField"

2024-09-11 22:19 UTC, mdnoble73 commented on data_dir_setup/solr7/open_archives/conf/schema.xml
> +<!--		<fieldType name="date" class="DatePointField"/>-->
It does for any field with a type of date. But the type of field for the date field gets changed below so we don't need to change the date type.

2024-09-12 13:00 UTC, Howell-Carnegie commented
I updated the files you had comments on.

2024-09-16 13:31 UTC, mdnoble73 requested changes
Can you fix the issue with James' changes being removed and resubmit against 24.10? Sorry, I'd love to get it into 24.09, but since release is tomorrow it feels like there isn't enough testing time.

2024-09-16 13:31 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/24.09.00.php
It looks like this commit removes some of the changes James made to the database updates.

2024-09-16 14:17 UTC, closed without merging

2024-09-16 14:34 UTC, Howell-Carnegie commented
Hi Mark,

I want to uncommit and remove my pull request of all of my changes (6
files) for this OpenArchives commit(s) but cannot find a way to do it. Then
I can resubmit them for 24.10.

*Jeremy Eden*
IT Manager
Howell Carnegie District Library
314 W Grand River, Howell, MI  48843
(517) 546-0720 x192 | (517) 546-4093 (fax)
www.howelllibrary.org


On Mon, Sep 16, 2024 at 9:32 AM Mark Noble ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Can you fix the issue with James' changes being removed and resubmit
> against 24.10? Sorry, I'd love to get it into 24.09, but since release is
> tomorrow it feels like there isn't enough testing time.
> ------------------------------
>
> On code/web/sys/DBMaintenance/version_updates/24.09.00.php
> <https://github.com/Aspen-Discovery/aspen-discovery/pull/2035#discussion_r1761163873>
> :
>
> It looks like this commit removes some of the changes James made to the
> database updates.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Aspen-Discovery/aspen-discovery/pull/2035#pullrequestreview-2306676372>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BKLRFW3FJJOJTFKBA7WDPA3ZW3MVRAVCNFSM6AAAAABNMZXH3OVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMBWGY3TMMZXGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-16 14:39 UTC, mdnoble73 commented
Looks like closing the PR worked. Do you need help updating your local system? If so I can slack or email you my calendar if you want to pick a good time to go over it.

2024-09-16 14:54 UTC, Howell-Carnegie commented
Did that fix James' missing changes?

*Jeremy Eden*
IT Manager
Howell Carnegie District Library
314 W Grand River, Howell, MI  48843
(517) 546-0720 x192 | (517) 546-4093 (fax)
www.howelllibrary.org


On Mon, Sep 16, 2024 at 10:40 AM Mark Noble ***@***.***>
wrote:

> Looks like closing the PR worked. Do you need help updating your local
> system? If so I can slack or email you my calendar if you want to pick a
> good time to go over it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Aspen-Discovery/aspen-discovery/pull/2035#issuecomment-2353118714>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BKLRFWY7KIEA7UYKOZUH5WTZW3UUXAVCNFSM6AAAAABNMZXH3OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNJTGEYTQNZRGQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2024-09-16 15:03 UTC, mdnoble73 commented
It didn't, it removed the pending PR though so you can resubmit.

2024-09-16 15:09 UTC, Howell-Carnegie commented
I'm confused on this because when I look at
https://github.com/Aspen-Discovery/aspen-discovery/blob/24.09.00/code/web/sys/DBMaintenance/version_updates/24.09.00.php
It
looks like James' changes are in there. Are the changes in a different file?

*Jeremy Eden*
IT Manager
Howell Carnegie District Library
314 W Grand River, Howell, MI  48843
(517) 546-0720 x192 | (517) 546-4093 (fax)
www.howelllibrary.org


On Mon, Sep 16, 2024 at 11:03 AM Mark Noble ***@***.***>
wrote:

> It didn't, it removed the pending PR though so you can resubmit.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Aspen-Discovery/aspen-discovery/pull/2035#issuecomment-2353182611>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BKLRFW4NVMNNOMZS54ACVADZW3XNLAVCNFSM6AAAAABNMZXH3OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNJTGE4DENRRGE>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>