24.10.00 cookie management
Aspen-Discovery/aspen-discovery pull request #2051
Opened 2024-09-09 11:19 UTC by AlexanderBlanchardAC

2024-09-17 16:23 UTC, AlexanderBlanchardAC commented
Test Plan

Check that default Local Analytics Tracking is altered based on Require Cookie Consent Storage
In the db, check the value of library->cookieStorageConsent. If you have just started Aspen, this should be 0 by default. 
Check the value of User-> userCookiePreferenceLocalAnalytics. This should be 1.
Navigate to Library Systems->Data Protection Regulations and check Require Cookie Storage Consent’. 
Once saved, recheck the db value of library->cookieStorageConsent, which should now be 1.
Recheck the db value of user->userCookiePreferenceLocalAnalytics, this should now be 0.

Check that data stored is cleared if library->cookieStorageConsent is enabled.
Start with library->cookieStorageConsent set to 0. 
Ensure the db has some local analytics data e.g. carry out a Summon search and click on some records so that the user_summon_usage table has some content. 
Navigate to Primary Configuration ->Library Systems->RequireCookieConsent and check the box. 
Once saved, use adb shell in your terminal. 
Navigate to /usr/local.aspen-discovery/code/cron
Run the following command: java -jar cron.jar test.localhostaspen
Recheck the user_summon_usage table, the data should be cleared. 
(This clears data if a library decides to instate the need to require cookie storage consent).

Ensure local analytics tracking does not occur if patron is not opted in:
Ensure Require Cookie Storage Consent is enabled -> Primary Configuration -> Library Systems -> Require Cookie Consent Storage.
In the cookie consent pop up choose ;’Essential Only’.
Ensure a module that uses analytics is enabled e.g. Summon.
Carry out a Summon search and click one of the records.
Check user_summon_usage, it should be empty. 
Navigate to ‘Your Privacy Settings’ in your account and turn on local analytics. 
Repeat the Summon search and click a record.
Check the db table it should now contain an entry. 

Ensure that local analytics data is cleared when a user opts out of local analytics:
Return to ‘Your Privacy Settings’ and opt out of local analytics. 
Recheck the db table, it should now be empty.

2024-09-18 08:24 UTC, AlexanderBlanchardAC commented
https://aspen-discovery.atlassian.net/browse/DIS-26

2024-09-27 22:26 UTC, mdnoble73 requested changes

2024-09-27 22:26 UTC, mdnoble73 commented on code/web/interface/themes/responsive/AJAX/cookieManagement.tpl
Several of these translations do not have isPublicFacing and/or isAdminFacing set so we see Translation Metadata not set properly. 
![image](https://github.com/user-attachments/assets/1791ca58-7e2a-4b4c-a11f-281f4b7431ab)

2024-09-27 22:26 UTC, mdnoble73 commented on code/web/release_notes/24.10.00.MD
> +### Privacy Updates
Can you add additional information about the cleanup of old analytics data when the user opts out or when the library opts out?

2024-09-27 22:26 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/24.09.00.php
Can you remove changes from this file?

2024-09-27 22:26 UTC, mdnoble73 commented on code/web/sys/LibraryLocation/Library.php
> +		if (empty($this->libraryId)) {
This should never be the case when called from update

2024-09-27 22:26 UTC, mdnoble73 commented on code/web/services/Websites/JSON.php
> +		$userObj = UserAccount::getActiveUserObj();
WE need to check here that there is an active user. Web Builder can be used anonymously as well. You can just reverse checking of userId and userWebsiteTracking

2024-09-27 22:26 UTC, mdnoble73 commented on code/web/services/Summon/JSON.php
> +		$userObj = UserAccount::getActiveUserObj();
Need to check if there is an active user before checking if they have analytics storage turned on.

2024-09-27 22:26 UTC, mdnoble73 commented on code/web/services/OpenArchives/JSON.php
> +		if ($userOpenArchivesTracking) {
Need to check if there is an active user before checking if they have analytics storage turned on.

2024-09-27 22:26 UTC, mdnoble73 commented on code/web/services/EBSCO/JSON.php
> +		if ($userEbscoTracking) {
Need to check if there is an active user before checking if they have analytics storage turned on.

2024-09-27 22:26 UTC, mdnoble73 commented on code/web/services/AJAX/JSON.php
> +			$userSummonUsage = new UserSummonUsage();
These can all do the batch delete as well rather than deleting each individual object

2024-09-27 22:26 UTC, mdnoble73 commented on code/web/interface/themes/responsive/MyAccount/temp.tpl
> +            <div id="cookieExplanation" style="display:none; margin-top:10px;">
Could we maybe add a setting within Library settings to either view a detailed list of things to be tracked or a statement the library can customize?

2024-10-01 02:31 UTC, mdnoble73 approved these changes

2024-10-01 02:37 UTC, merged