Github #2063: Debian installer - set max_input_vars = 5000
Aspen-Discovery/aspen-discovery pull request #2064
Opened 2024-09-18 20:15 UTC by lizrea

CentOS installer includes a php file that sets the max_input_vars to 5000 from the default 1000. Debian should also have this setting by default.

To test: 
Run aspen installer on Debian as if you were setting up a new Aspen, note that the /etc/php/${php_vers}/apache2/php.ini file has a max_input_vars of 1000

apply this patch, rerun the installer, note that the same file should now have max_input_vars of 5000.

2024-09-18 20:15 UTC, lizrea commented
please merge with the release notes PR coming just after this :)

2024-09-26 21:47 UTC, mdnoble73 requested changes

2024-09-26 21:47 UTC, mdnoble73 commented on install/installer_debian.sh
> +grep -q '^;max_input_vars = 1000' "$php_ini" || sed -Ei 's/^;max_input_vars = [0-9]+/max_input_vars = 5000/' "$php_ini"
It looks like this is looking for the commented out line, but not uncommenting it which means the new value would not apply. Is that your intention

2024-09-27 20:06 UTC, mdnoble73 commented on install/installer_debian.sh
> +grep -q '^;max_input_vars = 1000' "$php_ini" || sed -Ei 's/^;max_input_vars = [0-9]+/max_input_vars = 5000/' "$php_ini"
This also will not update existing installs. Is that needed?

2025-02-24 22:24 UTC, mdnoble73 commented
Closing, but implemented as part of https://aspen-discovery.atlassian.net/browse/DIS-431

2025-02-24 22:24 UTC, closed without merging