DIS-60: LibKey integration
Aspen-Discovery/aspen-discovery pull request #2158
Opened 2024-12-03 09:37 UTC by Chloe070196

Ticket: https://aspen-discovery.atlassian.net/browse/DIS-60

Test plans are found in commit messages

___________________________________________

**Description**:

This integration aims to allow libraries with a LibKey subscription to have direct links to full-text documents displayed on the eContent records shown in search results in Aspen, provided these records have a DOI.

Public

When viewing library catalogue search results of an eContent item-type, either on the search result page or on the detailed view page for a record, users can see an “Access Online” button:

if the LibKey API returned a direct link to the resource itself, then this takes the user directly to the full-text document, opening it in a new tab.

if the LibKey API does not return a direct link, this takes the user to the external page though which access to the resource can be obtained (this is the current default behaviour in Aspen).

On the detailed view page for the record, under the ‘Links’ section (if enabled), both the original link as found on the Marc record and the LibKey-issued link (if found).

Staff

Admin users can grant or remove the permission to administer the LibKey settings.

Admin users with the required permission can administer LibKey (CRUD, and the possibility to assign a specific LibKey set of settings to a specific location or library). The LibKey Settings are found under “Third Party Enrichment” in the Aspen Administration menu.

2024-12-03 16:48 UTC, mdnoble73 requested changes
Added several comments inline. My main concern is around performance and behavior if LibKey is not enabled. Currently the LibKey service will still be called even when not enabled.

2024-12-03 16:48 UTC, mdnoble73 commented on code/web/Drivers/LibKeyDriver.php
> +			$settings->fetch();
The fetch is not needed with the find(true) that automatically calls a fetch.

2024-12-03 16:48 UTC, mdnoble73 commented on code/web/Drivers/LibKeyDriver.php
> +		$curlWrapper = new CurlWrapper;
This section should not be done if there are no settings, should go into the if block.

2024-12-03 16:48 UTC, mdnoble73 commented on code/web/Drivers/LibKeyDriver.php
> +	public function extractDoi(string $url): string {
Should only doi urls be processed or does everything get processed?

2024-12-03 16:48 UTC, mdnoble73 commented on code/web/Drivers/LibKeyDriver.php
> +		$response = $curlWrapper->curlGetPage("https://public-api.thirdiron.com/public/v1/libraries/" . $settings->libraryId  . "/articles/doi/" . $this->extractDoi($doiUrl) . "?access_token=" . $settings-
Does the doi URL need any sort of encoding? Since that is a full URL I could see having a URL within the URL causing problems.

2024-12-03 16:48 UTC, mdnoble73 commented on code/web/RecordDrivers/MarcRecordDriver.php
> +			foreach($relatedUrls as $relatedUrl) {
For performance we should check if LibKey is enabled before checking all of the URLs.

2024-12-03 16:48 UTC, mdnoble73 commented on code/web/sys/Account/User.php
> +		$sections['local_enrichment']->addAction(new AdminAction('System Messages', 'System Messages allow you to display messages to your patrons in specific locations.', '/Admin/SystemMessages'), [
It looks like this was duplicated from the previous lines and is not needed.

2024-12-03 16:48 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/24.12.00.php
> +		'create_libkey_module' => [
Is the LibKey Module necessary?

2024-12-03 16:48 UTC, mdnoble73 commented on code/web/Drivers/LibKeyDriver.php
> +class LibKeyDriver {
We may be able to optimize some of the code by moving the functionality to get the LibKey link to the setting.

2024-12-03 17:49 UTC, Chloe070196 commented on code/web/Drivers/LibKeyDriver.php
> +	public function extractDoi(string $url): string {
I would say there is no point in processing urls that do not contain DOIs as LibKey requires DOI numbers.

Would we want to attempt to check whether urls contain DOIs early then, and add control flow so that the getLibKeyLink method is not called for those?

2024-12-03 17:53 UTC, Chloe070196 commented on code/web/sys/DBMaintenance/version_updates/24.12.00.php
> +		'create_libkey_module' => [
I was not entirely sure whether it would be - happy to remove it

2024-12-03 17:55 UTC, Chloe070196 commented on code/web/sys/Account/User.php
> +		$sections['local_enrichment']->addAction(new AdminAction('System Messages', 'System Messages allow you to display messages to your patrons in specific locations.', '/Admin/SystemMessages'), [
This looks like an incorrectly executed merge conflict resolution on my part - I'll remove it

2024-12-03 17:58 UTC, Chloe070196 commented on code/web/Drivers/LibKeyDriver.php
> +		$response = $curlWrapper->curlGetPage("https://public-api.thirdiron.com/public/v1/libraries/" . $settings->libraryId  . "/articles/doi/" . $this->extractDoi($doiUrl) . "?access_token=" . $settings-
I was hoping the extractDoi() method would negate this by only returning the DOI itself and removing the rest - but this might be an oversimplification of the issue on my end.

I take it the extractDoi() method needs to be updated?

2024-12-04 09:09 UTC, Chloe070196 commented on code/web/Drivers/LibKeyDriver.php
> +			$settings->fetch();
Thank you for reminding me of that, it'll be removed.

2024-12-04 09:12 UTC, Chloe070196 commented on code/web/Drivers/LibKeyDriver.php
> +		$curlWrapper = new CurlWrapper;
I have looked at inverting the logic so that if a setting is not found, then the getLibKeyLink method returns null early (immediately after the check) - would this be an acceptable solution?

2024-12-04 14:54 UTC, mdnoble73 commented on code/web/Drivers/LibKeyDriver.php
> +		$curlWrapper = new CurlWrapper;
Yep that would work

2024-12-04 14:55 UTC, mdnoble73 commented on code/web/Drivers/LibKeyDriver.php
> +	public function extractDoi(string $url): string {
Either way should be fine. I think we just want to avoid the call to the libkey server.

2024-12-04 14:56 UTC, mdnoble73 commented on code/web/Drivers/LibKeyDriver.php
> +		$response = $curlWrapper->curlGetPage("https://public-api.thirdiron.com/public/v1/libraries/" . $settings->libraryId  . "/articles/doi/" . $this->extractDoi($doiUrl) . "?access_token=" . $settings-
I'm not 100% sure. What do those URLs look like to start?

2024-12-04 15:12 UTC, Chloe070196 commented on code/web/Drivers/LibKeyDriver.php
> +		$response = $curlWrapper->curlGetPage("https://public-api.thirdiron.com/public/v1/libraries/" . $settings->libraryId  . "/articles/doi/" . $this->extractDoi($doiUrl) . "?access_token=" . $settings-
I would expect `https://doi.org/` followed by the DOI number, that's standard as far as I know, so that is the format I would expect all of them to follow.

If an item did contain just a DOI number in their Marc field 856 u, then it would end up as 'http://' followed by the DOI number (not a valid DOI URL format to my knowledge) by the time it hits the LibKey integration (unsure where this occurs). I did account for that potentially happening, but perhaps it is unnecessary.

2024-12-05 23:38 UTC, mdnoble73 approved these changes

2024-12-05 23:38 UTC, mdnoble73 commented on code/web/sys/DBMaintenance/version_updates/24.12.00.php
> +				"INSERT INTO permissions (name, sectionName, requiredModule, weight, description) VALUES ( 'Administer LibKey Settings','LibKey','LibKey', 0, 'Allows the user to administer the integration with L
This should be updated to not require the LibKey module since we removed that.

2024-12-05 23:38 UTC, mdnoble73 commented on code/web/Drivers/LibKeyDriver.php
> +		$settings->whereAdd("id=$activeLibrary->libKeySettingId");
This could be simplified to 
$settings->id = $activeLibrary->libKeySettingId
which will also take care of escaping fields properly rather than just adding a string. Not a big enough deal to prevent merging, but would be good to follow up on.

2024-12-05 23:45 UTC, merged