Koha showopacnote
Aspen-Discovery/aspen-discovery pull request #2175
Opened 2024-12-17 15:44 UTC by ammopt

Previously, when library's 'showOpacNote' was disabled, the Koha user's
opac note was still being displayed. This is because it's getting added
to _web_note regardless of the setting's value.
This patch removes the opacnote from Koha's getILSMessages, and adds the
setting check to when opacnote should be added to loadContactInformation
or not.

2024-12-17 20:53 UTC, mdnoble73 commented
Can you create a Jira ticket for this since, this changes when and where the note shows so I'd like to make sure we understand the implications.

2024-12-18 09:38 UTC, ammopt commented
Hi Mark, thank you, I 100% agree.
I've created the Jira ticket and provided a more in-depth explanation of the approach and why I went with it:
https://aspen-discovery.atlassian.net/jira/software/c/projects/DIS/boards/2?selectedIssue=DIS-137

2024-12-29 20:23 UTC, mdnoble73 requested changes

2024-12-29 20:23 UTC, mdnoble73 commented on code/web/Drivers/Koha.php
> -				if ($library->showOpacNotes) {
This is used in cases where _web_note is not set by calling loadContactInformation so we shouldn't remove this. Instead we could just rely on this function and remove setting _web_note in loadContactInformation. That will prevent showing duplicate messages as well.

2024-12-30 11:08 UTC, ammopt commented
Thank you for looking here, Mark. Sounds good, I've re-tested it myself, works, follow-up submitted.

2024-12-30 14:40 UTC, mdnoble73 commented
@ammopt can you update 25.01 release notes rather than 24.12 release notes?

2024-12-31 10:15 UTC, ammopt commented
> @ammopt can you update 25.01 release notes rather than 24.12 release notes?

Hi Mark, apologies, yes of course. Done.

2024-12-31 12:50 UTC, mdnoble73 approved these changes

2024-12-31 12:51 UTC, merged